[quote.epigraph, , John 14:6]
____
I AM the Way, and the Truth, and the Life.
____

[quote.epigraph, , Heb. 7:23]
____
Wherefore He is able also to save them to the uttermost,
that come unto God by Him.
____

== Memoir

Had the writer of the following Letters left an account of his religious experience,
his life, and pursuits, there is much reason to believe,
that such a memoir would have been very interesting and edifying.
The hand of another can but faintly describe,
the early and powerful visitations of Divine love extended to him; the exercises,
spiritual conflicts, and baptisms, which he had to pass through,
during the progress of his regeneration; the mercy and saving help vouchsafed to him,
in and by our Lord Jesus Christ, by whom, through faith and obedience,
he obtained the victory; and by whom, also,
he was qualified and enabled to labour that others
might be brought to the same happy experience.
Yet from an apprehension that to many who may read the Letters,
and who were not acquainted with the writer, a memoir of his life and character,
including a short notice of a few of his principal correspondents, would be acceptable,
many of his friends have wished that an account thereof might be given;
and having known John Thorp upwards of thirty years,
during which time I had frequent opportunities of enjoying his company and conversation,
and for the greater part of it an open and unreserved friendship with him,
several of my friends, whom I have great reason to esteem,
have repeatedly urged me to the undertaking.
I would gladly have had the work performed by one better qualified,
being sensible of my want of ability to do justice to the subject;
yet the regard I have for the memory of my friend,
and the desire which I feel to contribute (however feebly) to hand
down to posterity some memorial of one deservedly dear to me,
have finally prevailed upon me, so far as I may be enabled, to comply with the request.

It will be proper to observe,
that John Thorp`'s own memorandums furnish but very few materials for a memoir of himself;
and most of those who were acquainted with him in early life being deceased,
not much is now known respecting his conduct and character during that period,
except such circumstances as he hath occasionally
mentioned in conversation with his intimate friends.
To give this account something of the form of a continued narrative,
it may be necessary to introduce here a few particulars,
noticed in the testimony of Hardshaw-east Monthly Meeting.

John Thorp was born at Wilmslow, in the county of Chester, on the 5th of the 11th Month,
1742, N. S. He was the posthumous son of Jonathan Thorp, a farmer,
who left but little property.
The care of his maintenance and education, therefore,
with that of several other children, devolved on his mother,
whose maternal care and affectionate solicitude,
under the trying circumstances in which she was thus placed,
he frequently mentioned with feelings of filial gratitude.
His parents were members of the church of England,
in profession with which he was educated.
He was, from very early life, sensible of the workings of evil in his own heart,
and also of the manifestation of the Divine principle of light and grace,
which showed him the evil.
Possessing considerable energy of mind,
and but little disposed to submit patiently to those disappointments and trials,
to which, through life, mankind are universally subject, with some variety,
but with no exception; and self-will rising unrestrained to obtain its purpose,
he frequently experienced mortification and sorrow.
In this frame of mind he was led, at times, deeply to ponder,
whether or not this was the irrevocable lot of man,
and whether there was not a possibility of deliverance from such a state.
Here that adorable Mercy, which found our first father, after his transgression,
wandering in nakedness and want,
and in boundless compassion brought to him that promise of redeeming Love,
"`the seed of the woman shall bruise the serpent`'s head,`" visited,
in a remarkable manner, the subject of this memoir;
introducing him into a state of mental retirement,
and powerfully impressing his mind with that blessed
invitation and promise of the dear Redeemer,
"`Come unto me, all ye that labour and are heavy laden, and I will give you rest.
Take my yoke upon you, and learn of me: for I am meek and lowly in heart;
and ye shall find rest unto your souls.`"
He was made sensible that this world is not the place of rest for man,
but that it is intended for a probationary passage to, or preparation for,
a state of uninterrupted happiness hereafter;
and that this preparation can only be effected by the taking up of the
cross to all the corrupt desires and passions of fallen nature.

During these exercises,
he believed it to be required of him to decline the practice of singing,
in which he had taken great pleasure,
and had been a noted singer in that called the parish church of his native place;
but he continued some time longer to attend that place of worship.
Being now convinced that, as God is a spirit, and that they who worship Him,
must worship Him in spirit and in truth,
the forms and ceremonies practised there did not furnish
that edification and comfort which his soul longed for;
yet his regard for, and sense of duty to his tenderly affectionate mother,
made the thoughts of separating from her,
in the solemn and important duty of public worship, very trying to him; though at times,
when present with her, he was so much distressed,
and felt such strong convictions that he was not in his proper place, that,
to use his own words, his knees have been ready to smite together.

In reference to this season of his early^
footnote:[The time of this remarkable visitation is not clearly known,
but from several circumstances which he has occasionally mentioned,
it is probable that it was about hit fourteenth or fifteenth year.]
and Divine visitation, in a conversation with a religious person,
not a member of the Society of Friends, a few years before his decease,
he feelingly remarked, that he had never since, for a moment,
had to doubt the certainty or the source of those convictions which were thus,
at a very early age, so remarkably and so indelibly stamped on his mind;
that shortly afterwards, he attended a meeting of the people called Quakers, at Morley,
a village about two miles distant from his native place, where he found,
publicly professed and advocated, as the principles of a religious community,
doctrines consonant with the convictions which had operated so powerfully on his mind,
adding, that if he were only preserved in the way of his duty to the end,
which then could be at no great distance, he should have cause to rejoice,
and be thankful through eternity, that his lot had been cast amongst them.

It appears, by the records of Morley Monthly Meeting, that in the year 1762,
in the twentieth year of his age, he applied for,
and was received into membership by that Meeting.
For some years after his admission into the Society of Friends,
he had to pass through many and deep baptisms,
in being made willing to bear the cross patiently,
and to become an humble follower of a crucified Redeemer; to renounce the world,
with all its friendships and interests, the flesh, and the devil,
and daily to make war in righteousness against the enemies of his
soul`'s salvation--the pride and selfishness of his own heart.

He was often made sensible of the depravity of man,
how prone he is to feed upon vanity and pride, and that even in his best pursuits;
and to seek his treasure and comforts from earthly things,
instead of being willing to become as a stranger and a pilgrim on the earth; but,
by continuing in faithful obedience to the manifestations
of that Divine light by which he had been early visited,
he was often renewedly strengthened to offer up himself
an unreserved sacrifice to the Divine disposal,
and to petition the Father of all his mercies that
he would sanctify the offering to Himself.
In the seasons of his deepest temptations,
he was made to believe that he was not wholly forsaken of his God; that He,
who had condescended to visit him when he was as one lost and blind, would not leave him,
(if he continued faithful,) when he had become enamoured of His ways.
After many proving seasons,
he was brought to know an anchoring upon the everlasting Rock, Christ Jesus;
and it became more and more his delight to do the law of the Lord his God,
and to live continually as in His holy presence.
Thus he came to know the accuser to be cast down,
and to experience the glorious liberty of the sons of God.

In 1763 he removed to London, as appears by a short letter,
dated the 20th of the 9th Month in that year, addressed to an intimate friend.

From the circumstances in which his mother was left, by the death of his father,
it may reasonably be concluded that his education was comparatively limited; but,
however this might be,
his removal to London greatly facilitated his access to books and the means of information;
and possessing a comprehensive understanding, he very much improved himself,
during his residence there, in the knowledge of various branches of useful learning.
The following account of his conduct when in London, being well authenticated,
may be worthy of record.
A relation, who accompanied him from the country, and with whom he had joint lodgings,
and his oldest brother, an officer in the army, a man of talents and general knowledge,
formed, for some time, nearly the extent of his acquaintance.
With these companions, who were his superiors in information and learning,
and for whom he felt the attachment arising from relationship,
he at times delighted to converse; but, through Divine help,
he inflexibly resisted all their persuasions and entreaties to deviate,
in any one instance, from that steady and uniform religious practice of life and manners,
which he had believed it to be his duty to adopt.
He occasionally accompanied them in an evening`'s walk;
but if they gave way to any levity of conduct,
or turned aside into any tavern or place of diversion, he immediately left them,
and returned to his lodgings.

He continued to reside in London about four years, living much retired;
yet he was known to some valuable Friends, by whom he was esteemed.
In the latter part of the year 1767, he removed to Manchester,
where he continued to reside to the end of his days.

On the 4th of 9th Month, 1769, he married Martha, daughter of John Goodier,
of Morley Meeting, by whom he had two sons--Samuel, who died in infancy, and John,
who is now living.
She was removed from him by death, after the short union of four years,
which event he has been heard to mention as a peculiarly exercising affliction.

For several years after he had settled at Manchester,
there does not appear to be much further to remark upon,
except that he continued under a deep religious exercise and concern,
that nothing might be permitted to obstruct or retard his
progress in that way which leadeth to the heavenly kingdom;
pressing "`toward the mark, for the prize of the high calling of God in Christ Jesus.`"
Under the influence of these impressions,
he believed it right for him to keep his temporal concerns in a small compass,
steadily declining offers that were made to induce
him to embark more extensively in business;
desiring neither lot nor inheritance in the land;
asking only a passage through this world in peace, with "`food to eat,
and raiment to put on.`"
During this period, he was favoured with the kind regard of some valuable Friends,
among whom he has particularly mentioned that excellent
minister of the gospel Sarah Taylor.
She was concerned to sympathize with him in his spiritual exercises,
and to encourage him to continue in faith and patience;
she being persuaded that he was under the preparing Hand for service in the church.

Having fulfilled the "`weeks of preparation,`" and
"`eaten the roll of prophecy,`" he was,
by the great Master, called to the work of the ministry.
The exact time when he first appeared in this service, is not now known,
but it was about the year 1773.
His first communication in the ministry was a revival
of that prophetic declaration of Isaiah,
"`Strangers shall stand and feed your flocks,
and the sons of the aliens shall be your ploughmen and your vine-dressers.`"
His early testimonies, as a minister, were mostly short;
but being delivered in the renewed openings and authority of the Word of Life,
they were to edification,
and give satisfactory evidence that he was rightly qualified for that important service.
In 1775, he took his seat in the Meeting of Ministers and Elders, as an approved minister.
Being careful to occupy with the talents which he had received,
he was favoured to experience an increase of his gift,
and to be made an able minister of the New Testament,
"`not of the letter but of the spirit.`"

In the 7th Month, 1775, he married, to his second wife, Martha,
the daughter of Thomas Cash, of Morley, and sister to Thomas Cash of the same place,
of whom there is an account in the tenth volume of "`Piety Promoted.`"
By this wife he had seven children, four of whom died in their infancy,
and three of them survived him.

Between 1775 and 1781, under the influence of a great degree of sympathy,
and in the love of the gospel, he addressed several letters to Frances Dodshon,
who was at that time under deep spiritual trial and depression.
Most, if not all, of these letters, will be found in this publication;
and as the language of encouragement in them is peculiarly strong,
it is thought that the following short notice of the friend to whom they were written,
will not be unacceptable to the reader.

Frances Dodshon was descended from a respectable family near Leek, and was born in 1714.
Her parents were possessed of a considerable estate,
and were in profession with the church of England.
She possessed a good understanding,
and had been educated in all those accomplishments
which were deemed necessary to her rank in society.
About the twentieth year of her age,
she was so fully and availing convinced of the principles of truth as professed by Friends,
that in the most trying seasons of her life, as she was often heard to say,
the foundation of those principles could never be shaken.
Soon after being united in membership with the Society of Friends,
she was called to the work of the ministry,
for which she was well qualified by her Lord and Master.
Whilst health and ability were afforded, she laboured much in the exercise of her gift,
travelling into most parts of England, Scotland, and Wales.
Her openings were clear in the doctrine and authority of the gospel,
and communicated with lively zeal.
She was frequently led to speak to the states of individuals;
and there is no doubt but her labours were blessed
to the spiritual help and edification of many.
In the course of her warfare through this vale of tears, she had,
both spiritually and temporally, to combat with many afflictions; yet in all,
and through all, she was hiddenly supported by Him,
in whom she had most assuredly believed.
Her deepest trials were occasioned by the apprehension
that she was forsaken by the Beloved of her soul;
yet was the language of a deeply tried servant expressive of the exercise of her spirit:
"`My righteousness I hold fast, and will not let it go.`"
The following extract from one of her letters to John Thorp,
will show the tried state of her mind:

Dear and truly sympathizing Friend,

I seem to myself guilty of ingratitude in being so long silent,
after receiving so valuable and encouraging an epistle from thee,
which I often read with close attention,
and with humble and fervent desire to be helped to lay hold
of some degree of that living faith and hope,
thou so fully and feelingly expressest thyself to be favoured with on my behalf,
and which I endeavour to encourage my drooping spirit
in concluding would not be the case with thee,
or my dear friend Sarah Taylor, or any of the living in Israel, if I were really,
(as I am painfully tempted to fear) totally cast off or forsaken by the Father of Mercies.
Yet, although I consider things in the most favourable light my afflicted state will admit,
and esteem it, as I justly ought to do, a favour which I cannot be too thankful for,
to be thus under the notice, tender regard,
and deep travel in spirit of many faithful souls,
it is beyond expression what I yet suffer, for want of the evidence,
or revival of living faith and hope in my own mind, that the Lord will again return,
and show mercy to my disconsolate, imprisoned soul, which goes mourning all the day long,
and cannot be comforted, because the blessed Comforter, He who alone can deliver my soul,
seems yet afar off; and the cruel accuser almost continually at hand,
to bear down and frustrate my utmost endeavours to
draw near to the Fountain of help and strength,
to be enabled to lay hold of hope and faith to resist the fiery darts of the wicked one.

Oh! my dear friend,
could I but hope that I am of the number thou mentionest of the Lord`'s chosen ones,
whose names are written in the Book of Life, I should esteem no baptism too deep,
nor any suffering too long, or too great to endure.
But herein lies my great discouragement, that I seem, in my own painful apprehension,
to suffer as an evil-doer, or one who,
through inattention and want of due circumspection, has offended an all-gracious Being,
and caused Him to withdraw His blessed presence, light, life, and holy Spirit;
and oh! what in this stripped, desolate state has the poor soul to cleave to,
or flee to for refuge and support, as the experienced Psalmist says,
"`If the foundations be destroyed, what can the righteous do?`"
They have not another to go unto, nor can expect preservation, comfort, or help,
but from Him who they experimentally know hath the word of eternal life,
and also the key of David, and alone can open their shut-up state,
and by His powerful voice say, even to the spiritually dead, "`Come forth;`" then,
and not till then, can we feel our spirits quickened by Him,
who is of a truth the resurrection and the life of every truly living soul,
that lives to and in Him.

Frances Dodshon lived to advanced age, and during the latter years of her life, she was,
at seasons, by the power of Divine love and light,
raised above the deep depression before described;
and when of ability to attend meetings,
was at times enabled to preach the gospel with life and power.

There is abundant cause to believe that,
in the earlier as well as the latter stages of religions experience, our heavenly Father,
in His wisdom and mercy,
is often pleased to suffer His most approved servants to be deeply
tried with an abasing sense of their helplessness and unworthiness;
to withdraw the light of His countenance, and to leave them sorrowful and forlorn,
and all with the gracious design of furthering the work of their sanctification.
In these seasons of tribulation,
they may be strongly tempted to listen to the accusations of the enemy,
and to distrust the Lord`'s faithfulness and love;
but whether these trials originate in natural or spiritual causes,
John Thorp`'s letters to Frances Dodshon will, there is no doubt,
long continue to cheer and animate many a doubting and fearful pilgrim.

John Thorp did not believe himself to be called to travel so much in the
work of the ministry as many others of his fellow-labourers have done,
yet he was frequently concerned, under the influence of gospel love,
to visit his Friends in the neighbouring meetings, both in Lancashire and Cheshire,
and he took some longer journeys on the same account.
In the year 1784, accompanied by his friend Martha Routh, of Manchester,
he paid a religious visit to the families of Friends of Penketh Meeting,
and immediately after to the families of Friends in Warrington; Rebecca Wright,
from America, joining them in the visit, and Sarah Reynolds, of Penketh,
to part of the families.
From Warrington he proceeded to visit the families of Langtree and Ashton Meetings,
Martha Routh and Sarah Reynolds continuing with him.
In the discharge of this service, it appears, from information received,
that he was much favoured.

In 1787, in company with his ancient and beloved friend Sarah Taylor,
he visited the families of Friends belonging to Liverpool Meeting.
In 1789,
he united with Deborah Darby and Rebecca Young in a similar
visit to the families of Friends of Manchester Meeting.

In the 8th Month of 1792, died his highly valued friend Richard Shackleton, of Ballitore,
in Ireland, in the sixty-sixth year of his age, between whom,
and the subject of this memoir,
a near friendship and valuable correspondence had subsisted for several years,
and to whom several letters in this volume are addressed.

Richard Shackleton was a man who possessed strong natural powers of understanding,
improved by a liberal education,
and these being sanctified and brought into subjection to the cross of Christ,
he became qualified for distinguished usefulness in the church.
He filled, for many years the station of an Elder with great propriety,
being eminently furnished, by his Divine Master,
with wisdom and ability to communicate encouragement
and counsel to such as stood in need.
The sense which John Thorp had of the church`'s and his own loss,
from the decease of his friend,
appears by a letter which he addressed soon after that event to Abraham Shackleton,
and which, coming to the publisher`'s hands too late to be inserted in its proper place,
may not unsuitably be introduced here:

John Thorp to A. Shackleton (upon the death of his father, Richard Shackleton)

1792+++.+++

In justice to thee and myself,
I ought sooner to have acknowledged my gratitude for thy condescension,
in writing to me the particulars of my dear friend thy father`'s decease.
Looking at the church militant, his death is a loss to all but himself.
I sympathize with you, I feel for the church,
and regret my particular share in the general loss;
his company was to me exceedingly pleasant and lovely.
I felt, almost at all times when with him, a more than common union with him;
as a man and Christian, I loved him dearly.

I rejoice in that I was much favoured with his company.
At our last Yearly Meeting, he condescended to go with me, or take me with him often,
in the evenings.
I prized the opportunities,
and treasure up his remarks as the fruit of experience and mature judgment.
I am thankful for the share he allowed me in his friendship;
for the instructive opportunities I have had of his conversation,
and for the valuable letters I have received from him, by all which I desire to improve.

Give my dear love to thy mother;
it is likely her separation from him will be but of short duration.
I have no doubt she will soon be with him in the kingdom of Divine joy.
With regard to the deceased, doubtless, our loss is his gain.
I feel something like congratulation with him,
as having arrived safe at the desired port,
and entered into the fruition of the glorious reward of good labours.
May a double portion of that Spirit which made him bright and useful,
rest on all his children, that they may not only walk worthy of such a father,
but of that high and holy vocation wherewith we are called, by our heavenly Father,
to glory and virtue.
To the guidance and protection of Israelis Shepherd, I recommend thee,
and all thy father`'s house, desiring He may have you always in his keeping.

I am, with the salutation of love to thyself, thy family, and sisters,
thy affectionate friend,

John Thorp.

In the 8th Month of 1793, John Thorp attended the funeral of his friend Frances Dodshon,
who died at Macclesfield, and was there interred.
About the 11th Month of this year,
he visited the families of Friends in Manchester Meeting, having Martha Routh,
before-mentioned, and also his friend Mary Robinson, a minister of the same meeting,
as companions in the service.

About the close of the year 1797, in company with Martha Routh,
he again visited the families belonging to his own meeting; and soon after,
they performed a similar visit to the families of Morley Monthly Meeting.

In the 8th Month, 1802, he left home for London.
Whilst there, he sat with Friends in all the meetings in the metropolis,
and was at several of those in the neighbourhood.
He returned home by Coventry, Warwick, and Birmingham.
This journey he mentions in a letter to Richard Reynolds, dated 12th Month 3d.

In the summer of 1806, he wholly declined business, having,
through the good providence of God, a sufficiency for his future support.
In the 8th Month of this year, he lost, in the sixty-first year of her age,
his faithful and affectionate companion, to whom he had been united thirty-one years;
she had been-in a declining state of health for some months.
This loss he very sensibly felt,
and has feelingly described in a letter to Richard Reynolds, dated 8th Month 21, 1806.

In the year 1808, after attending the Yearly Meeting,
he visited all the meetings in the metropolis, and several of those in the vicinity.
He left London the 17th of 6th Month, arrived at Bristol the following day,
and continued there until the 1st of 7th Month,
attending meetings as they came in course.
From Bristol he went to Worcester, where he was at the meetings on First day;
and on the Third day following he went to Coalbrookdale;
after attending several meetings at this place, he returned home, taking, in his way,
the Monthly Meeting at Shrewsbury.
In many of the meetings, on this journey, he was silent; but in others he was enabled,
by his Lord and Master, to preach the gospel in the demonstration of the spirit,
and with power, greatly to the comfort and rejoicing of many.

In the year 1812, he found his mind drawn, in gospel love,
to unite with Priscilla Hannah Gurney and Susanna Naish,
in a religious visit to the families of his own meeting.
They had one hundred and nineteen sittings, and accomplished the work in twenty-nine days.
At the conclusion of this visit,
he accompanied the same friends in a similar one to the Friends of Morley Monthly Meeting.
The last service, of this kind, in which he was engaged,
was with John Bottomley and Elizabeth Bludwick, in the year 1813,
when he accompanied them to most of the families of his own meeting.
He was then in his seventy-first year.
Whilst ability of body was afforded,
he continued in the practice of visiting the neighbouring meetings,
as he felt himself drawn thereto by his Divine Master.

He was frequently invited to attend marriages and burials at a distance.
At such times, he was careful to seek for Divine counsel,
that he might be preserved from complying with,
or declining such invitations in his own will.
He has sometimes mentioned, to his intimate friends,
his regret at what appeared to him an over earnestness, manifested by some,
for the company of ministers on such occasions.

His powers of expression were strong and persuasive,
and these being made subservient to his great Master`'s cause, he became,
through the power of Divine love,
eminently qualified affectionately to entreat others
to come to that Fountain of Mercy and saving help,
by which he had been often refreshed and strengthened.

To those who, in their Christian pilgrimage, had to go mourning on their way,
whose hands were often ready to hang down,
he was many times a "`son of consolation,`" encouraging them, in an animating manner,
to keep hold of faith and patience, and still to hope that He,
who had been their morning light, would be their evening son.
But the subject that formed the most prominent and frequent exercise in his gospel labours,
was closely to recommend to all, an earnest, serious,
and impartial examination into the state of their own hearts,
to see how their accounts stood with God; and to set forth,
how great and irreparable will be the loss to those
who unwisely neglect the opportunity afforded,
of embracing the all-sufficient means appointed of God for their redemption.

He was often concerned, in his public communications,
to turn the attention of his hearers from himself to the subject;
and to direct them to look to God, instead of the instruments, for instruction and help,
for want of which he believed that many suffer much loss.
He was very exemplary in his movements in the ministry, and frequently,
especially when at home, sat meetings in silence.

He spent much time in retirement,
a practice which he recommended to all religiously disposed persons.
It was his practice, during a great part of his life, to take a walk, mostly alone,
in the forepart of the day, generally into the fields.
These walks, taken with much regularity, there is reason to believe,
often proved seasons of religious exercise and devotion; and some,
who have casually met with him, have been struck with the solemnity of his countenance.

His reading had been extensive and various, and was to him a source of much satisfaction.
In the former part of his life more especially, he read, with close attention,
the writings of early Friends,
and carefully informed himself of the creeds of the various religious professors;
but the writings which he read most frequently, (next to the Holy Scriptures,
which he greatly preferred to all other books,) were those, by whomsoever written,
which treated of religion, as being an individual, experimental work,
consisting in obedience, and not in speculative knowledge or in mere profession.
Yet, notwithstanding the satisfaction that reading afforded him, he was fully sensible,
and often remarked, how little all the knowledge that can be obtained,
even from the best of books,
will avail those who neglect a reverent attention
to the Divine law written in their own hearts.
During the closing years of his life, he confined himself very much to the New Testament,
and to a work well known amongst the Society of Friends, entitled "`Piety Promoted.`"

He mixed but little with general society,
and to strangers there was probably in his appearance something like reserve;
yet he had much pleasure in the company of his friends.
In conversation, he united innocent cheerfulness with Christian gravity.
Possessing a retentive memory, and a mind well stored with useful information;
and having a peculiarly strong, clear, and apt mode of expressing his sentiments,
his company was very interesting.
He had a particular enjoyment in the society of such as he believed
to be his fellow-pilgrims in seeking a better country.
With many of these,
(and his view was very far from confining the number of them to the religious
Society of which he was a member,) he maintained an intercourse,
of which there are living witnesses who can testify,
that it was to them a source of blessing.

He frequently visited, as in a casual way,
many of the Friends of his own meeting and of other meetings in the neighbourhood.
To these visits he appears to have been often drawn by the influence of Divine love,
as in many of them, he was enabled, pertinently and impressively,
to communicate much instructive counsel.

He was favoured with an excellent constitution of body, and with uninterrupted health,
which continued, with but little alteration, until the autumn of 1815,
when he was visited with a slight attack, apparently of the paralytic kind, which,
in some degree, impaired his powers of body and mind;
yet his understanding remained clear to the last,
and he continued to attend his own meeting as usual.
He was able to walk about, and visit his friends,
and his mind appeared to dwell in Divine love.

The last time he appeared in the ministry was in 1816,
at a funeral which was attended by a considerable concourse of people.
On this occasion he was, in a very feeling manner,
enabled to call the attention of those present to the uncertainty of life,
and the necessity of being prepared for death.
At the grave side, he addressed the widow, who was left with a numerous young family,
in the language of the prophet: "`Leave thy fatherless children,
I will preserve them alive, and let thy widows trust in me.`"

In the 9th Month, 1816, his beloved friend Richard Reynolds, of Bristol,
departed this life, in the eighty-first year of his age.
Of this distinguished philanthropist, the character is generally known;
but as all may possibly not be acquainted with it,
a short account of him may serve to elucidate some passages of those letters,
in the following collection, which were addressed to him.

Richard Reynolds was, for many years, extensively engaged in the Iron trade,
by which he very considerably increased his wealth.
Under the influence of religious principle, he was sensible of his responsibility to Him,
to whom belongeth "`the earth,
and the fulness thereof;`" and his heart being enlarged in love to God,
and good-will to men, it is believed that,
after taking from his large income sufficient only for bis own moderate establishment,
he devoted the whole of the remainder to charitable purposes.
His beneficence was guided by great wisdom,
which rendered the benefit still more extensive.
His benevolence raised the admiration of all who knew him;
yet he was far from being elated by this circumstance, or by the possession of wealth;
and in the distribution of his bounty,
he frequently concealed the hand which sent the relief.
He was a truly humble-minded Christian,
and was often tried with a deep sense of spiritual poverty.
He had also a very low view of the stewardship committed to him, which he,
on one occasion, described to a friend in the following terms:
"`My talent is the meanest of all talents, a little sordid dust;
but the man in the parable who had but one talent, was accountable,
and for the talent that I possess, humble as it is,
I also am accountable to the great Lord of all.`"
This good steward was favoured to experience an increasing
and well-grounded confidence in the mercy of God,
through the ever-blessed Redeemer, which he thus expressed in a letter,
written only a few days before his decease: "`I have done with this world,
and all my happiness in it is from the hope that I shall
soon have it where there is neither sin nor sorrow;
and that hope rests entirely on the mercy of God,
and the merits and mediation of Jesus Christ.`"
The end of this man was peace.

John Thorp survived the death of his friend Richard Reynolds about twelve months,
during which period he frequently mentioned the prospect of his own dissolution.
About a week before his decease, he was seized with a severe spasmodic affection.
At this time, he manifested great composure of mind, saying that,
whichever way it might terminate, all would be well.

The evening preceding his decease, he related to his family the following circumstance,
which occurred in his youth,
and which it is not known that he had ever before communicated: indeed, he very rarely,
even in his own family, or with his most intimate friends,
made himself the subject of conversation: "`When a boy, about fourteen years of age,
my attachment to music and singing was such,
that when walking alone in the lanes and fields on an evening,
I frequently gratified myself by singing aloud; and indulged therein,
even after my mind became uneasy with the practice, until,
in one of my solitary evening walks, and when in the act of singing, I heard, as it were,
a voice distinctly say, '`If thou wilt discontinue that gratification,
thou shall be made partaker of a much more perfect harmony.`'`" Such was
the powerful and convincing effect of this solemn and awful communication,
that, he added, he never afterwards indulged in the practice.
In relating this short and, to those about him, interesting anecdote of his early youth,
he was, towards the latter part of it, considerably affected,
and could not suppress his tears,
which appeared as the tears of gratitude to God at this
remembrance of his very early merciful visitation.

After a short suspense of conversation,
he related the circumstance of Luke Cock having been a great singer,
prior to joining the Society of Friends; and that John Richardson said of him,
"`he was the greatest singer in that part of the country where he resided,
and that he sung then the songs of Babylon, by the muddy waters thereof;
but having drunk deep of the brooks of Shiloh,
which run softly into the newly converted soul,
he could sing and rejoice in the Lord Jesus Christ.`"
Whilst communicating this anecdote, he continued much affected, and m tears,
and his manner of relating it was most impressive and Solemn.

He conversed cheerfully with his family during the remainder of the evening.
The following day, being the 30th of the 9th Month, 1817,
about five o`'clock in the afternoon, whilst sitting in his chair,
he closed his eyes and quietly departed.

John Bradshaw.

Manchester, 10th Month 81, 1820.
