[#reflect, short="Reflections on the Conditions of Mankind"]
== Reflections on the allotments of Providence in the varied conditions of Mankind.

The Lord is the All-wise Disposer of events; He maketh rich, and maketh poor: (it is God,
saith Moses,
that giveth men power to get wealth.) He exalteth and abaseth at His pleasure;
and though I do most firmly believe, that God "`doth not afflict willingly,
nor grieve the children of men;`" that He is a God of mercy, and knoweth all our wants,
as well as our weaknesses, and will add all that His wisdom sees best,
to those who first seek His kingdom, and the righteousness thereof;
yet am I forced to confess, with regard to His respective outward,
as well as inward administrations of prosperity and adversity,
His judgments are unsearchable, "`and His ways past finding out,`"

It is obvious, I own, that trouble is often the result of our own perverseness,
and arises from the determination of an unsanctified will,
the imprudence of our undertakings, and folly of our choice; but then, I think,
it is equally evident, that they sometimes arise from a different source,
and must necessarily be resolved into the unerringly
wise and inscrutable providence of God.
What shall we say of Job, that perfect man`'s condition?
what of the hunger, thirst, and nakedness of the Apostles?
what of those who wandered about "`in sheep-skins and goat-skins, being destitute,
afflicted, tormented, of whom the world was not worthy?`"
and what of the holy, lowly Jesus, who had not where to lay His head?

The like hath been the situation of many true disciples
and Christians of the purest ages;
and since, of many of the first Reformers, who have lived in valleys and desolate places,
and who hare been true successors of the Apostles in nakedness and want,
treated as the off-scouring of all things, and to whom, indeed,
the earth has been as iron, though the heavens have not been as brass.
Far, very far, be it from my heart to conclude these unhappy,
or to think they had cause to complain.
Surely they were supremely blessed,
and received in this life recompense a thousand-fold for all their sufferings;
but I instance them, to evince that even the favourites of heaven, as well as those who,
through disobedience, frustrate the designs of Divine mercy, may be, and sometimes are,
tried with a scarcity of the outward accommodations of this life.

Riches, surely, are not certain marks of Divine favour,
nor prosperity an evidence that our ways please God.
Doth he not sometimes give men their heart`'s desire,
and withal send leanness into their souls?
We are apt to call providences by wrong names.
Afflictions, "`more precious than gold that perisheth,`" we call curses;
and riches we call blessings, when, for once they are so,
it is to be feared they are sent of God a thousand times for judgements.
The distresses and troubles of Israel of old were often administered in mercy,
when the people had, in fulness and prosperity, revolted from God,
to bring them back again to Him, to trust and depend upon Him,
and have their expectation from Him;
and if this be the gracious design of the Almighty now,
in the administration of distress and adversity, as I fully believe it often is,
I am sure that such trials deserve to be considered as evidences of His merciful regard,
who in this, though severe, yet more intelligible language to earthly hearts,
is seeking to convince us of our dependance on Him, relation to Him,
and that it is He who can bless or blast all our endeavours.

I have often thought, and it hath been confirmed in my mind,
that if we were but more attentive,
and disposed to obey the secret intimations of the "`wonderful
Counsellor,`" who speaks from heaven in our hearts,
we should happily make it less necessary for the Lord to
speak to us so frequently in the language of affliction.
Oh! if this were but enough our case,
(and I am sure it is above all things to be desired,)
we should thereby avoid every snare,
and be enabled happily, in the line of duty, to go forward in the lot of our appointment;
and then, though our dwellings might be with the lowly,
and we should have to labour for daily bread, yet, divested of anxious care,
we should rest secure in His providence, who numbereth the hairs of our heads,
clothes the lilies with transcendent beauty, and hears the young lions when they cry.

If thus we were concerned to worship the Lord our God,
to bless Him in the lot He hath appointed us, He would bless our bread and our water;
and if consistent with His will, and the designs of His wisdom,
He can increase our corn and oil, and multiply our gold and silver.
Indeed, cross occurrences, adverse providences, or afflictions, however administered,
have not always their desired or intended effects:
so the Lord complained formerly--"`I have smitten you with blasting and mildew,`"
"`yet have ye not returned unto Me.`" There is an aptness in the human mind (which
sees not beyond things that are natural) to rest in second causes;
and, blind to the discriminating providence of the Most High,
to fix the blame on secondary agents; but surely,
"`affliction cometh not forth of the dust,
neither doth trouble spring out of the ground.`"

Oh that, through the medium of Divine Light,
we might look up to God! therein we should discover the
secret turnings of His holy hand in all these things;
for I am fully persuaded, that, whatever is permitted to try us, whatever dispensations,
inwardly or outwardly, we may be under,
it is the dispensation of unerring Wisdom and Goodness; and the very best for us,
the greatest blessing we are capable of receiving in our present state of mind,
consistent with our chiefest good.
Oh! what cause have we, therefore, to commit ourselves wholly to Him,
to bless His name in every dispensation, who is the sole Arbiter of heaven and earth,
who superintends the universe, whose goodness and power are equal;
who knows all situations, and is ever graciously administering to every one of us,
in uniform mercy and goodness, what is most convenient for us,
and all for this most desirable, most glorious purpose, to redeem,
to gather us to Himself, who is the fulness of blessing and of life.

[.signed-section-signature]
John Thorp.
