[#testimony-hardshaw, short="Testimony from Hardshaw-East Meeting"]
== A Testimony from the Monthly Meeting of Hardshaw-East, concerning JOHN THORP, Deceased.

Our beloved friend John Thorp was born at Wilmslow, in the country of Chester,
the 5th of the 11th Month, 1742,
according to the N. S. His parents were in profession with the church of England.
His father dying before he was born, the care of his education,
with that of several other children, devolved on his mother, who,
we have reason to believe, was a sober, well-minded woman,
for whom he retained an affectionate and honourable esteem.

We have but little information respecting his conduct when a boy, except that,
at a very early age,
he became a singer in that called the parish church at his native place,
an exercise which he was then strongly inclined to;
but being soon after favoured with a visitation of "`the dayspring from
on high,`" he believed it to be required of him to relinquish this practice,
in which he had taken great delight;
and during a season of distress and mental retirement from the world,
it pleased the Father of mercies, by the secret operation of his Divine Power,
to open to hie mind the nature and spirituality of the gospel dispensation;
and to convince him that the saving knowledge of God is only to be attained
by the immediate revelation and inspiration of the Holy Spirit.

Some time after, he began to attend the meeting of Friends at Morley,
about two miles distant from the place of his birth.
This he did in a way to be as little observed as possible.
There he found, publicly professed and advocated,
the important doctrines which had been so clearly, and, as he has since declared,
so immovably impressed on his mind.

Continuing to attend the meetings of Friends, and feeling unity with them, he was,
in the twentieth year of his age, admitted into membership.
The following year he removed to London, where he continued to reside about four years,
and, in the year 1767, he removed to Manchester, settled there,
and not long after entered into the married state.

For some years after his admission into our Society,
he had to pass through much deep exercise and spiritual conflict, finding in himself,
much that was opposed to that state of humble resignation which had been,
by the Divine light, so clearly opened to his view, as necessary to be attained; but,
through the powerful and effectual operation of the grace of God,
he was enabled to take up his cross, to follow Christ in the regeneration,
and to experience a preparation for that work and
service in the church whereunto he was appointed.

About the thirty-second year of his age, he appeared in the work of the ministry.
He was naturally a man of strong mind, and a comprehensive understanding;
and being faithful to the gift received,
he became an able and powerful minister of the gospel,
reverently careful to wait for the renewed openings of the Word of Life;
so that we believe it may be truly said of him, that, when he ministered,
he did it of the ability which God gives,
approving himself a workman that needs not to be ashamed;
rightly dividing the word of truth;
faithfully warning the careless and worldly-minded of their danger;
encouraging the sincere and upright-hearted; and, to the mourners in Zion,
he was indeed a "`son of consolation;`" and, through the Divine blessing,
his labours were made instrumental to the spiritual advantage of many.

His labours in the work of the ministry were mostly confined within
the compass of his own Quarterly Meeting and his native county;
except that he several times attended the Yearly Meeting in London,
and twice visited the meetings of Friends in the metropolis and its neighbourhood,
the latter time, returning by way of Bristol.
He several times visited the families of Friends in his own meeting,
a service for which he was well qualified.

He was frequently concerned to testify,
that the way to the kingdom of heaven is the way of humility, of self-denial,
and the cross;
the way which the Captain of our salvation has trodden before us and sanctified.
In this respect our beloved friend was an eminent example;
being early and deeply convinced of the danger of seeking
for the treasures and possessions of this world,
he was content to remain in a comparatively low station.
That he might not be unnecessarily encumbered with the cares of this life,
and that he might be more at liberty for the service of his Divine Master,
he steadily declined, at a time when he had an increasing family,
the earnest and repeated solicitations of some of
his near relations to enter into more extensive business;
yet he was favoured to experience the gracious promise of our blessed Lord fulfilled,
that to those who seek first the kingdom of God and His righteousness,
all things necessary shall be added.

He was greatly and generally beloved; and among his more intimate friends,
his natural cheerfulness, tempered with Christian gravity,
his deep experience and sound judgment in Divine things,
rendered his conversation peculiarly interesting, instructive, and edifying.

In the autumn of 1815, he was visited with a slight attack of the paralytic kind,
by which his powers of body and mind were in some degree impaired;
yet he was diligent in attending his own meeting,
and was much pleased with the company of his friends,
to whom his conversation continued to be interesting and edifying,
clearly evincing his concern for the welfare of the church,
and that his mind was centered in Divine Love.

About a week before his decease, he was seized with a severe spasmodic affection.
At this time he manifested great composure of mind, saying that,
whichever way it might terminate, all would be well.
Continuing in a state of patient resignation, as one having done his day`'s work,
and waiting for his Master`'s call,
being supported by that faith and confidence in the
mercy of God through our Lord Jesus Christ,
which he so feelingly described sometime before in a letter
to a friend in which he expressed himself as follows:
"`At seasons,
I feel a degree of consolation and Divine peace that cannot be expressed in words,
which I would not exchange for a thousand times the treasures of both the Indies;
in comparison of which I should esteem, I do esteem,
crowns and sceptres as dung and dross.
And at the much more frequent seasons, when heavenly good is least sensibly felt,
(I hope I write it with humble, heartfelt gratitude,) my faith, and hope,
and confidence, are so firmly anchored on the everlasting Rock Christ Jesus,
that when the rains descend, and the winds and the storms beat, I am not greatly moved.
I know Him in whom I have believed,
and that He will in mercy keep all those who have committed themselves to him.`"

The evening preceding his dissolution, he conversed cheerfully; with his family,
and mentioned that he thought it a great favour to be removed without much bodily suffering.
The following day, being the 30th of the 9th Month, 1817,
about five o`'clock in the afternoon, while sitting in his chair, he closed his eyes,
and gently stretching himself, quietly departed; and has, we have no doubt,
joined that innumerable multitude which John beheld, who came out of great tribulation,
and have washed their robes and made them white in the blood of the Lamb.
His remains were interred the 6th of the 10th Month following,
in Friends`' burial-ground at Manchester,
after a large and solemn meeting held on the occasion.
He was aged about seventy-five, and a minister about forty-three years.

Given forth by the Meeting aforesaid, held at Manchester the First of the Fourth Month,
1818, and signed in and on behalf thereof, by

+++[+++69 members of the Meeting]

Read and approved in our Quarterly Meeting for Lancashire, held at Manchester,
the Second day of the Fourth Month, 1818, and in and on behalf thereof, signed by

George Crosfield, Jun.
Clerk.

Signed on behalf of the Women`'s Meeting by

Elizabeth Crewdson, Clerk.
