== A Prayer.

+++[+++The paper from which this Prayer is taken, is in John Thorp`'s handwriting,
and bears this inscription: "`On third day, the 21st of 10th Month, 1794,
the following Prayer was raised in my heart, and the expression of it required.`"
It appears, on an examination, that on the day mentioned,
Hardshaw Monthly Meeting was held at Liverpool.]

[.small-break]
'''

Oh Lord God Almighty, conscious that we are but dust, and that You are holy,
that as is Your Majesty, so is Your mercy; we beseech You, look down upon us in mercy,
whom You have raised up, to set Your name among.
Take us under Your care, and exercise Your discipline upon us.
Turn Your hand again and again upon us;
"`revive Your work in the midst of the years,`" that both the dross, and the tin,
and the "`reprobate silver,`" may be taken away from us.
Purge our camps, O Lord, we beseech You,
and remove from us everything that is offensive to You; that so we may,
according to Your blessed purpose,
become "`as lights in the world,`" as "`the salt
of the earth,`" as waymarks to the people,
as faithful standard bearers for You.

And inasmuch as it has pleased You, O Lord God Almighty,
to pour forth Your judgements in the earth, we pray You, if it be Your will,
to search by them, not only the present, but all succeeding generations.
Overturn and remove everything that obstructs the coming of Your kingdom.
Grant that Your government and dominion may spread from sea to sea,
and from the rivers to the ends of the earth.

Look down, O Lord, in mercy and compassion, on all sorts and conditions of men.
Remember the poor oppressed Africans;
pour forth upon them the blessings of Your light and peace,
and remove oppression from them.
Hasten, O Lord, the accomplishment of that which You have spoken,
that "`from the rising of the sun, even unto the going down of the same,
Your name should be great among the Gentiles,
and in every place incense should be offered unto Your name,
and a pure offering:`" that so, O Lord,
all the ends of the earth may take the cup of Your salvation,
and be enabled acceptably to ascribe to You, glory and honour, thanksgiving and praise,
might, majesty, and dominion, forever and ever.
Amen.
