[short="Memoir of Joseph Harwood"]
== A Memoir of Joseph Harwood, of Manchester.

[.chapter-subtitle--blurb]
+++[+++Written by John Thorp]

[.centered]
_"`The righteous shall be had in everlasting remembrance,
but the name of the wicked shall rot.`"_

[.small-break]
'''

Joseph Harwood was born at Bolton in Lancashire, in the year 1712,
where his parents lived in good repute,
his father being a conscientious professor of the Church of England,
and a man of integrity and circumspection,
who was acquainted with the nature and work of religion,
and who knew and professed it to be an inward work.

From his father he, in early life, received the rudiments of a religious education;
and though he lost his parents when he was about sixteen or seventeen years of age,
yet his father`'s piety and instructions had made
such deep and lasting impressions on his mind,
that they always remained fresh and legible,
and were to him as bread cast upon the waters.
As he advanced in years,
he became more and more acquainted with the conflicts
and probations which attend the Christian warfare;
so that as he arrived at mature age,
he became a man of sorrows and acquainted with grief.

In this state he entered into the army,
from the very unusual motive of being more at leisure to attend to the duties of religion;
but in this he soon found himself mistaken, though he continued therein for many years.
Here, he became as a wonder and a byword to his companions, who,
seeing his distress and anxiety of mind, and being strangers to the inward cause,
formed various and wild conjectures concerning him.
Nevertheless, such were his sobriety, docility, and readiness to serve,
that he gained the esteem and confidence of his officers,
and was principally employed in their particular service.

He continued in the army about fifteen years, a good example,
beloved and esteemed in that station,
having been in several engagements and acquitted himself with fidelity and reputation.

But the Lord God of his life, who had graciously visited him in early age,
and continued to follow him in mercy and judgement, with the rod, yet in love,
thereby preparing him for the further dispensation
and revelation of the Gospel of love and peace,
now revealed to him, with incontestible clearness,
the total inconsistency of all wars and fightings with the whole nature
and design of the glorious Gospel of our Lord and Saviour Jesus Christ.

Long had he been acquainted and conflicted with the
policy and force of the enemies of his own house;
but now, being called and required by the pure principle of life and peace,
to lay down his arms in conformity to His doctrine and example, who came,
not to destroy men`'s lives, but to save them,
and who has commanded us to love our enemies, to pray for them,
to forgive their trespasses unto "`seventy times seven;`" and,
that whatsoever we would that they should do to us, to do the same to them: when,
through the prevalence of the love of God,
our friend was brought into a good degree of conformity to these divine precepts,
not only in notion and sentiment, but renewed hereunto out of a state of fallen nature,
through the arising and gradual growth of the life of Jesus Christ in himself,
he was made willing to submit to whatever suffering
or loss might be the consequence of his obedience,
though no less a punishment was impending than the loss of his natural life.
For the further proving of his faith,
the enemy was permitted to avail himself of every instrument concerned in his trial,
in whom he appeared indeed as a "`Red Dragon`" raising
the most frightful and formidable opposition.
But in vain are all the united strength and efforts of the powers of darkness,
when opposed to the invincible strength of Him who is Almighty: whatever be the policy,
opposition, or rage of the adversary and his agents,
the Lamb and His followers are sure to have the victory.
Although his trial was as in the "`fiery furnace,`" yet being inwardly supported
and protected by one in the form of "`the Son of man,`" his life was preserved,
and his liberty and discharge were freely granted; yes,
so signally did divine providence interpose in his behalf,
that upon his trial by the Court Martial, some who had been his fiercest opposers,
became his advocates, and candidly represented his case to King George 2nd,
who honourably gave him his discharge.

He afterwards joined in society with the people called Quakers,
and came to reside in Bolton, the place of his nativity,
where he made a public profession of the truth as professed by them,
and walked in it with all circumspection; but after his residence there about a year,
apprehending his vocation for that place fulfilled, he came to settle in Manchester,
where he mostly lived, the remaining part of his life, greatly beloved and esteemed.

About the fortieth year of his age, he received a gift in the ministry,
the exercise of which, and in company with other ministers,
he travelled in various parts of this nation, as also of Scotland and Ireland;
in all which places his labours were acceptable,
tending to stir up the pure mind and to beget faith in that Divine
Light and Holy Leader in which he had most surely believed,
and by which he had been guided into all necessary truth,
and to gather and fix the attention of the people to the same.
He was singularly serviceable in his own meeting,
labouring for the edification of his brethren in the most holy faith,
walking in wisdom towards them that are without,
giving none occasion of offence either to Jew or Gentile, or to the church of God.

As a good soldier of Christ, he endured the difficulties allotted to him,
and was careful not to entangle himself with the cares of this life,
walking soberly as in the day,
keeping in view "`the mark of the prize of the high calling of God in
Christ Jesus,`" whereby he was enabled to make straight steps to his feet,
being a good example to the flock of Christ.
As his heart with his treasure was in heaven,
and his affections were set on things above,
so was his conversation frequently there also; for, though he was naturally cheerful,
yet his words were often seasoned with the salt of the covenant,
evidently ministering grace to the hearers.
In constant and timely attendance of meetings, he was careful and diligent,
and therein not an idle spectator, but a fervent and steady labourer,
in the ability received for the arising and prevalence of divine life;
and though his public testimonies were neither large,
nor in the "`enticing words of man`'s wisdom,`" yet he was frequently
baptized into a feeling of the various states and conditions of the people,
and often had a word in due season to deliver, "`in the demonstration of the spirit,
and of power;`" yes, right careful was he in this important point of Gospel ministry,
to feel, when he stood up to minister to others, the renewings of power from on high,
the fresh supply of holy oil according to his measure,
and his engagements raised and sealed by the Spirit of God upon his own mind; so,
that his words, thus coming from the Fountain of excellency and power,
of love and wisdom,
were many times as "`apples of gold in pictures of silver,`" and
raised the evidence in the minds of those who heard him,
that he spoke "`as one having authority,`" though not like the scribes.

And as his heart was enlarged in the love of God beyond many others,
so was he frequently drawn forth therein to visit the families
of his friends in Manchester and its neighbourhood,
to see how it fared with them in the best things; when, from easy, innocent conversation,
he was often drawn into solemn silence;
and in such opportunities he frequently appeared in seasonable exhortations, admonitions,
and counsel; his doctrine dropping as the dew, and his speech as the small rain.
As his heart was thus drawn forth in love towards his brethren,
so was he also greatly beloved by them; and met with much esteem, respect,
and a kind reception from all ranks and classes of the people,
among whom it might be truly said, he went from house to house,
breaking bread with thankfulness and singleness of heart.
He was exemplary in what the apostle defines to be "`pure religion and undefiled,
before God and the Father,`" visiting the fatherless and widows in their afflictions;
and few I believe were more happily preserved from the spots of this world.
Having passed through a variety of states in the course of his religious attainments,
being acquainted both with heights and depths,
having known the devices of Satan and the terrors of the Lord, he was qualified,
by experience, to speak a word in season to them which were weary,
having frequently to tell to others what the Lord in mercy had done for his soul.
I have this further to remark concerning our dear deceased friend,
that he stretched not himself beyond his measure,
was not solicitous after forbidden knowledge,
nor attempted to be wise above what is written; but his study was to be quiet, to know,
and faithfully to do his own business;
thus was he preserved to the conclusion of his time, a steady, bright example,
and an ornament to the church.
Having fulfilled his course and accomplished his warfare, being in peace with God,
and full unity with his brethren,
he was removed from his earthly tabernacle to the mansion prepared for him, where,
we have no doubt,
he lives and ever will live to unite with all the Heavenly
Host in the just tribute of an everlasting Hallelujah.

He departed this life in the 64th year of his age, on the 12th,
and was buried in Friends`' burying ground, at Manchester, the 14th day of 1st Mo. 1776.

[.signed-section-signature]
John Thorp.
